
	export const CREATE_BOOK_SUCCESS = 'CREATE_BOOK_SUCCESS';
	export const FETCH_BOOKS_SUCCESS = 'FETCH_BOOKS_SUCCESS';
	export const FETCH_BOOK_BY_ID_SUCCESS = 'FETCH_BOOK_BY_ID_SUCCESS';

	export const ADD_TO_CART_SUCCESS = 'ADD_TO_CART_SUCCESS';
	export const FETCH_CART_SUCCESS = 'FETCH_CART_SUCCESS';

	export const LOG_IN_SUCCESS = 'LOG_IN_SUCCESS';

	export const SET_LOGIN_PENDING = 'SET_LOGIN_PENDING';
	export const SET_LOGIN_SUCCESS = 'SET_LOGIN_SUCCESS';
	export const SET_LOGIN_ERROR = 'SET_LOGIN_ERROR';

	//For admin
	//1/Projects
	export const PROJECTLISTS = 'PROJECTLISTS';
	export const DETAILPROJECT = 'DETAILPROJECT';
	export const CLIENTLISTS = 'CLIENTLISTS';
	export const PRO_STATUSLIST = 'PRO_STATUSLIST';
	export const EDIT_PROJECT = 'EDIT_PROJECT';
	export const ADD_PROJECT = 'ADD_PROJECT';
	export const DELETE_PROJECT = 'DELETE_PROJECT';

	// COMPANY LIST
	export const COMPANYLISTS = 'COMPANYLISTS';
	export const COMPANYTOTALRECORDS = 'COMPANYTOTALRECORDS';

   // ACTIVITY LIST
		export const ACTIVITYLIST = 'ACTIVITYLIST';
		export const ACTIVITYINFO = 'ACTIVITYINFO';
		export const ACTIVITYPROJECTLIST = 'ACTIVITYPROJECTLIST';
		export const ACTIVITYPROJECTLISTCANJOIN = 'ACTIVITYPROJECTLISTCANJOIN';
   //CLIENTS
   export const CLIENTLIST = 'CLIENTLIST';
   export const CLIENTINFO = 'CLIENTINFO';
   export const CLIENTPROJECTS = 'CLIENTPROJECTS';
   export const NEWVALUE = 'NEWVALUE';
   //EMPLOYEES
   export const EMPLOYEESLIST = 'EMPLOYEESLIST';
   export const EMPLOYEEINFO = 'EMPLOYEEINFO';
   export const EMPLOYEEPROJECTLIST ='EMPLOYEEPROJECTLIST';
   export const EMPLOYEEPROJECTSAVAILABLE ='EMPLOYEEPROJECTSAVAILABLE';
   export const EMPLOYEESTATE ='EMPLOYEEPROJECTLIST';
   export const EMPLOYEESTYLE ='EMPLOYEEPROJECTLIST';
   export const EMPLOYEEINFO_ITEM = 'EMPLOYEEINFO_ITEM';
   export const EMPPROJECT_JOIN = 'EMPPROJECT_JOIN';
   export const EMPPROJECT_SPLICE = 'EMPPROJECT_SPLICE';
   
